name: message-queue
services:
  scheduler:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: [ "python", "src/scheduler.py" ]
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: [ "python", "src/worker.py" ]
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 2
    depends_on:
      - scheduler
      - postgres

  postgres:
    image: postgres:latest
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
      - ../db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
